export const ADD_PRODUCT='ADD_PRODUCT'
export const ADD_PRODUCT_SUCCESS='ADD_PRODUCT_SUCCESS'
export const ADD_PRODUCT_ERROR='ADD_PRODUCT_ERROR'

export const START_DOWNLOAD_PRODUCTS='START_DOWNLOAD_PRODUCTS'
export const DOWNLOAD_PRODUCTS_SUCCESS='DOWNLOAD_PRODUCTS_SUCCESS'
export const DOWNLOAD_PRODUCTS_ERROR='DOWNLOAD_PRODUCTS_ERROR'

export const OBTAIN_PRODUCT_DELETE='OBTAIN_PRODUCT_DELETE'
export const PRODUCT_DELETE_SUCCESS='PRODUCT_DELETE_SUCCESS'
export const PRODUCT_DELETE_ERROR='PRODUCT_DELETE_ERROR'

export const OBTAIN_PRODUCT_EDIT='OBTAIN_PRODUCT_EDIT'
export const START_PRODUCT_EDIT='START_PRODUCT_EDIT'
export const PRODUCT_EDIT_SUCCESS='PRODUCT_EDIT_SUCCESS'
export const PRODUCT_EDIT_ERROR='PRODUCT_EDIT_ERROR'

export const SHOW_ALERT='SHOW_ALERT'
export const CLOSE_ALERT='CLOSE_ALERT'